name:                IceLang
version:             0.1.0.1
github:              madorama/IceLang
license:             MIT
author:              madorama
maintainer:          madorama999@gmail.com
copyright:           2023 madorama

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madorama/IceLang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- megaparsec
- parser-combinators
- mtl
- utf8-string
- bytestring
- text
- pretty-simple
- prettyprinter
- directory
- time
- ansi-terminal

ghc-options:
- -Wall
- -Werror=incomplete-record-updates
- -Werror=incomplete-patterns
- -Werror=incomplete-uni-patterns
- -Werror=partial-fields
- -Werror=identities
- -Werror=monomorphism-restriction
- -Wno-type-defaults
- -Wcompat

default-extensions:
- ConstrainedClassMethods
- DataKinds
- DefaultSignatures
- DoAndIfThenElse
- DuplicateRecordFields
- FunctionalDependencies
- LambdaCase
- MultiWayIf
- NoFieldSelectors
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- RecordWildCards
- Strict
- StrictData
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src

executables:
  IceLang-exe:
    main:                Main.hs
    source-dirs:         app

    dependencies:
    - IceLang
    - optparse-applicative

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

language: GHC2021

